pip install psutil --break-system-packages
pip install get-mac --break-system-packages
pip install PyQt6 --break-system-packages
pip install sphinx-rtd-theme --break-system-packages
pip install netifaces --break-system-packages
pip install paramiko --break-system-packages
pip install psycopg2-binary --break-system-packages
pip install matplotlib --break-system-packages
pip install PyQtChart --break-system-packages